/**
 * lib/identity-colors.ts
 *
 * Accessible text values for the content-driven identity hues.
 *
 * The hues themselves are identity: a ministry's colour, a series' colour.
 * They are fine as decorative fills, but every one of them fails WCGA AA as
 * TEXT on a light surface — measured, worst-case against #ffffff and
 * #f4f6f9:
 *
 *   emerald 1.78   amber 1.98   kids 2.11   adults 2.17   slate 2.37
 *   violet  2.51   missions 2.72   college 3.53   students 3.74
 *   #5b7fa6 3.86   #8b6fae 3.89
 *
 * and four of them fail on the dark surfaces too. So each hue gets a pair,
 * generated by mixing toward black (light) or white (dark) only as far as
 * needed to clear 4.6:1 against the worst surface in that theme — which
 * keeps each hue recognisably itself rather than collapsing them all to the
 * same dark. A uniform mix was tried first and rejected: at the 60% needed by
 * emerald, #4a7fcb landed at 8.01:1, so the hues stopped being
 * distinguishable from each other, which defeats the point of having them.
 *
 * Seven of the eleven pass untouched in dark mode and are listed with the raw
 * hue on that side, deliberately — not an oversight.
 *
 * ADDING A HUE: supply both values. `npm run verify:identity` checks them.
 */

export interface IdentityInk {
  /** The hue itself. Decorative fills only — the 1px identity bar, a dot. */
  hue: string;
  /** Accessible as text on --surface / --surface-sunken. */
  light: string;
  /** Accessible as text on the dark surfaces. */
  dark: string;
  /**
   * Safe as a FILL under white text (>=4.6:1), and theme-invariant.
   * A filled identity button must not invert: the light-mode fill is the dark
   * one, so inverting it would put white text on a pale fill — the exact
   * failure this table exists to prevent. The raw hue is not usable here;
   * white on #4a7fcb measured 4.05:1.
   */
  solid: string;
}

export const IDENTITY: Record<string, IdentityInk> = {
  kids:     { hue: "#c9a84c", light: "#836d31", dark: "#c9a84c", solid: "#8c722a" },
  students: { hue: "#4a7fcb", light: "#4170b3", dark: "#6290d2", solid: "#3c75c7" },
  missions: { hue: "#e07b54", light: "#a65b3e", dark: "#e07b54", solid: "#c45024" },
  college:  { hue: "#9b6ecc", light: "#845ead", dark: "#a67ed2", solid: "#8f5dc6" },
  adults:   { hue: "#4ab8c4", light: "#317981", dark: "#4ab8c4", solid: "#2d8089" },
  steel:    { hue: "#5b7fa6", light: "#527295", dark: "#7492b3", solid: "#55789d" },
  plum:     { hue: "#8b6fae", light: "#7d649d", dark: "#9c85ba", solid: "#8568aa" },
  amber:    { hue: "#f59e0b", light: "#9a6407", dark: "#f59e0b", solid: "#a26807" },
  emerald:  { hue: "#34d399", light: "#1f7c5a", dark: "#34d399", solid: "#1d845f" },
  violet:   { hue: "#a78bfa", light: "#7763b2", dark: "#a78bfa", solid: "#7e55f8" },
  slate:    { hue: "#94a3b8", light: "#66707f", dark: "#94a3b8", solid: "#627693" },
};

/**
 * The inline custom properties `.identity-ink` and `.identity-border` read.
 * Spread onto the element that needs the accessible value:
 *
 *   <span className="identity-ink" style={inkVars(IDENTITY.kids)}>Ages 0–5</span>
 *
 * A brand token works here too — `inkVars({ hue: "", light: "var(--accent-text)",
 * dark: "var(--accent-text)" })` — so entries that already point at a token
 * flow through the same path instead of needing a second code branch.
 */
export function inkVars(ink: Pick<IdentityInk, "light" | "dark">): React.CSSProperties {
  return {
    "--identity-light": ink.light,
    "--identity-dark": ink.dark,
  } as React.CSSProperties;
}
