/**
 * lib/identity-colors.ts
 *
 * Accessible text values for the content-driven identity hues.
 *
 * The hues themselves are identity: a ministry's colour, a series' colour.
 * They are fine as decorative fills, but every one of them fails WCGA AA as
 * TEXT on a light surface — measured, worst-case against #ffffff and
 * #f4f6f9:
 *
 *   emerald 1.78   amber 1.98   kids 2.11   adults 2.17   slate 2.37
 *   violet  2.51   missions 2.72   college 3.53   students 3.74
 *   #5b7fa6 3.86   #8b6fae 3.89
 *
 * and four of them fail on the dark surfaces too. So each hue gets a pair,
 * generated by mixing toward black (light) or white (dark) only as far as
 * needed to clear 4.6:1 against the worst surface in that theme — which
 * keeps each hue recognisably itself rather than collapsing them all to the
 * same dark. A uniform mix was tried first and rejected: at the 60% needed by
 * emerald, #4a7fcb landed at 8.01:1, so the hues stopped being
 * distinguishable from each other, which defeats the point of having them.
 *
 * Seven of the eleven pass untouched in dark mode and are listed with the raw
 * hue on that side, deliberately — not an oversight.
 *
 * ADDING A HUE: supply both values. `npm run verify:identity` checks them.
 */

export interface IdentityInk {
  /** The hue itself. Decorative fills only — the 1px identity bar, a dot. */
  hue: string;
  /** Accessible as text on --surface / --surface-sunken. */
  light: string;
  /** Accessible as text on the dark surfaces. */
  dark: string;
  /**
   * Safe as a FILL under white text (>=4.6:1), and theme-invariant.
   * A filled identity button must not invert: the light-mode fill is the dark
   * one, so inverting it would put white text on a pale fill — the exact
   * failure this table exists to prevent. The raw hue is not usable here;
   * white on #4a7fcb measured 4.05:1.
   */
  solid: string;
}

export const IDENTITY: Record<string, IdentityInk> = {
  kids:     { hue: "#c9a84c", light: "#836d31", dark: "#c9a84c", solid: "#8c722a" },
  students: { hue: "#4a7fcb", light: "#4170b3", dark: "#6290d2", solid: "#3c75c7" },
  serve:    { hue: "#5cb87a", light: "#3e7b52", dark: "#5cb87a", solid: "#408155" },
  missions: { hue: "#e07b54", light: "#a65b3e", dark: "#e07b54", solid: "#c45024" },
  college:  { hue: "#9b6ecc", light: "#845ead", dark: "#a67ed2", solid: "#8f5dc6" },
  adults:   { hue: "#4ab8c4", light: "#317981", dark: "#4ab8c4", solid: "#2d8089" },
  steel:    { hue: "#5b7fa6", light: "#527295", dark: "#7492b3", solid: "#55789d" },
  plum:     { hue: "#8b6fae", light: "#7d649d", dark: "#9c85ba", solid: "#8568aa" },
  amber:    { hue: "#f59e0b", light: "#9a6407", dark: "#f59e0b", solid: "#a26807" },
  emerald:  { hue: "#34d399", light: "#1f7c5a", dark: "#34d399", solid: "#1d845f" },
  violet:   { hue: "#a78bfa", light: "#7763b2", dark: "#a78bfa", solid: "#7e55f8" },
  slate:    { hue: "#94a3b8", light: "#66707f", dark: "#94a3b8", solid: "#627693" },
};

/**
 * The inline custom properties `.identity-ink` and `.identity-border` read.
 * Spread onto the element that needs the accessible value:
 *
 *   <span className="identity-ink" style={inkVars(IDENTITY.kids)}>Ages 0–5</span>
 *
 * A brand token works here too — `inkVars({ hue: "", light: "var(--accent-text)",
 * dark: "var(--accent-text)" })` — so entries that already point at a token
 * flow through the same path instead of needing a second code branch.
 */
export function inkVars(ink: Pick<IdentityInk, "light" | "dark">): React.CSSProperties {
  return {
    "--identity-light": ink.light,
    "--identity-dark": ink.dark,
  } as React.CSSProperties;
}

/* ------------------------------------------------------------------------- *
 * Derivation, for hues that arrive as DATA.
 *
 * The table above is hand-tuned because those hues are fixed and few. Series
 * and speaker accents are not: they come from content, so no table can cover
 * them, and every one of them lands in the same trap — a mid-chroma brand hue
 * is legible as a fill and illegible as 10px text on white. Fourteen call
 * sites were painting a raw data hue as text; on a light card the default
 * brand cyan measured 2.73:1.
 *
 * So the same method the table was built with is expressed as a function:
 * mix toward black (light) or white (dark) only as far as needed to clear
 * 4.6:1 against the WORST surface in that theme. Feeding the twelve table
 * hues through it returns the hand-tuned values -- nine byte-identical, three
 * off by a single hex digit -- which is the check that the function and the
 * table agree rather than two different ideas of the same thing.
 *
 * The two grounds are literals because this module is bundled and cannot read
 * tokens.css at runtime. `npm run verify:identity` asserts they are still the
 * worst light and dark surfaces, so a token change cannot silently invalidate
 * the derivation.
 * ------------------------------------------------------------------------- */

/** Worst (darkest) light surface: --surface-sunken. Guarded by verify:identity. */
export const WORST_LIGHT_GROUND = "#f4f6f9";
/** Worst (lightest) dark surface: --surface-overlay, dark. Guarded by verify:identity. */
export const WORST_DARK_GROUND = "#1b2738";

const TARGET = 4.6;

const rgbOf = (s: string): [number, number, number] => {
  const h = s.replace("#", "").trim();
  const f = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  return [0, 2, 4].map((i) => parseInt(f.slice(i, i + 2), 16)) as [number, number, number];
};
const chan = (c: number) => {
  const v = c / 255;
  return v <= 0.04045 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
};
const lum = (c: [number, number, number]) =>
  0.2126 * chan(c[0]) + 0.7152 * chan(c[1]) + 0.0722 * chan(c[2]);

/** WCAG 2.1 contrast ratio between two opaque colours. */
export function contrast(a: string, b: string): number {
  const [x, y] = [lum(rgbOf(a)), lum(rgbOf(b))];
  const [hi, lo] = x > y ? [x, y] : [y, x];
  return (hi + 0.05) / (lo + 0.05);
}

const asHex = (c: number[]) =>
  "#" + c.map((v) => Math.round(v).toString(16).padStart(2, "0")).join("");

/**
 * Walk `hue` toward `end` in 1% steps and stop at the first tone that clears
 * TARGET. Stepping (rather than solving) is deliberate: it stops at the FIRST
 * passing tone, so the result stays as close to the original hue as the
 * requirement allows, which is what keeps twelve hues distinguishable from
 * each other instead of collapsing toward the same dark.
 */
function toward(
  hue: string,
  end: [number, number, number],
  test: (candidate: string) => number,
): string {
  const from = rgbOf(hue);
  for (let t = 0; t <= 1.0001; t += 0.01) {
    const c = asHex(from.map((v, i) => v + (end[i] - v) * t));
    if (test(c) >= TARGET) return c;
  }
  return asHex(end);
}

const BLACK: [number, number, number] = [0, 0, 0];
const WHITE_RGB: [number, number, number] = [255, 255, 255];

/**
 * Accessible ink for a hue that came from content rather than the table above.
 * Pass the result to `inkVars` exactly like a table entry.
 */
export function deriveInk(hue: string): IdentityInk {
  return {
    hue,
    light: toward(hue, BLACK, (c) => contrast(c, WORST_LIGHT_GROUND)),
    dark: toward(hue, WHITE_RGB, (c) => contrast(c, WORST_DARK_GROUND)),
    solid: toward(hue, BLACK, (c) => contrast("#ffffff", c)),
  };
}

/**
 * Accessible ink for a hue over ONE known ground, when that ground is also
 * data-driven (a series hero paints its own background colour, so neither
 * theme tone is the right answer -- the ground is whatever the content says).
 * Lightens or darkens away from the ground, whichever direction the ground
 * requires.
 */
export function inkOn(hue: string, ground: string): string {
  const goDark = contrast("#ffffff", ground) < contrast("#000000", ground);
  return toward(hue, goDark ? BLACK : WHITE_RGB, (c) => contrast(c, ground));
}

/** `deriveInk` + `inkVars` in one call, for a data hue on a themed surface. */
export function inkVarsFor(hue: string): React.CSSProperties {
  return inkVars(deriveInk(hue));
}
