// ── Sermon library ──────────────────────────────────────────────────────────
// Real sermon data pulled from BBC YouTube playlist (PLmi1s4e0rk_5Mm_vS6JWamVhtkrhfpKt7).
// This is the static fallback — once sermons are entered in Sanity Studio (/studio),
// this file is bypassed automatically (app/sermons/page.tsx switches when Sanity has data).

export interface Sermon {
  id: string;
  youtubeId: string;   // YouTube video ID — thumbnail + link derived from this
  title: string;
  series: string;
  seriesId: string;    // slug — used to group sermons by series
  speaker: string;
  date: string;        // ISO format: "YYYY-MM-DD"
  passage: string;
  book: string;
  duration?: string;
  description?: string;
  passages?: string[];  // additional scripture references from sermon notes
}

export const SERMONS: Sermon[] = [

  // ── Behind the Scenes (Esther) — current series ────────────────────────────
  {
    id: "bts-8",
    youtubeId: "",
    title: "Named and Known",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-09-20",
    passage: "Selected Scriptures",
    book: "Esther",
  },
  {
    id: "bts-guest-0913",
    youtubeId: "Y3Exv0qAz0Y",
    title: "Mark 8",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Paul Christensen",
    date: "2026-09-13",
    passage: "Mark 8",
    book: "Mark",
  },
  {
    id: "bts-7",
    youtubeId: "E4CZ5kOuabw",
    title: "Choosing to Remember",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-09-07",
    passage: "Esther 9–10",
    passages: ["Esther 9", "1 Corinthians 2:2", "1 Corinthians 15:3-4", "Galatians 6:14", "Hebrews 12:3"],
    book: "Esther",
  },
  {
    id: "bts-6",
    youtubeId: "XzVcw5oW704",
    title: "The Great Reversal",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-08-31",
    passage: "Esther 7–8",
    passages: ["Esther 7", "Daniel 4:37", "Psalm 30:11-12", "Exodus 15:1-3", "1 Samuel 2:4-6"],
    book: "Esther",
  },
  {
    id: "bts-5",
    youtubeId: "yGxu7qN5EBk",
    title: "The Unlovable Villain",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-08-24",
    passage: "Esther 5–6",
    passages: ["Esther 4", "Psalm 7:14-16", "Romans 3:11-12", "Ephesians 2", "Titus 3:3"],
    book: "Esther",
  },
  {
    id: "bts-4",
    youtubeId: "btbqBK07-vk",
    title: "What Is Your Destiny?",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-08-17",
    passage: "Esther 4",
    passages: ["Esther 4", "Joel 2"],
    book: "Esther",
  },
  {
    id: "bts-3",
    youtubeId: "9QDjTUzMK-E",
    title: "Seeing a Thread",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-08-10",
    passage: "Esther 2–3",
    passages: ["Esther 2:21-3", "Esther 3", "1 Samuel 30", "Judges 3", "1 Samuel 15"],
    book: "Esther",
  },
  {
    id: "bts-2",
    youtubeId: "Fvzqf7jNsKE",
    title: "More Than Meets the Eye",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-08-03",
    passage: "Esther 2",
    passages: ["Psalm 46:1-3", "Proverbs 21:1", "Daniel 2:21", "Psalm 135:6", "Exodus 2:23-25"],
    book: "Esther",
  },
  {
    id: "bts-1",
    youtubeId: "tHm_f7onEDQ",
    title: "The King Exposed",
    series: "Behind the Scenes",
    seriesId: "behind-the-scenes",
    speaker: "Curtis Hill",
    date: "2026-07-27",
    passage: "Esther 1",
    passages: ["James 1:21", "Psalm 2"],
    book: "Esther",
  },

  // ── The Prayer That Shapes Us ───────────────────────────────────────────────
  {
    id: "prayer-3",
    youtubeId: "lcGm3J8LAeM",
    title: "Temptation and Deliverance",
    series: "The Prayer That Shapes Us",
    seriesId: "prayer-that-shapes-us",
    speaker: "Micah Frink",
    date: "2026-07-20",
    passage: "Matthew 6",
    book: "Matthew",
  },
  {
    id: "prayer-2",
    youtubeId: "0hMRNDYFXX8",
    title: "Daily Bread and Sin",
    series: "The Prayer That Shapes Us",
    seriesId: "prayer-that-shapes-us",
    speaker: "Josiah King",
    date: "2026-07-13",
    passage: "Matthew 6",
    book: "Matthew",
  },
  {
    id: "prayer-1",
    youtubeId: "eJ84c_OWwT0",
    title: "Focusing Our Prayers",
    series: "The Prayer That Shapes Us",
    seriesId: "prayer-that-shapes-us",
    speaker: "Curtis Hill",
    date: "2026-07-06",
    passage: "Matthew 6",
    passages: ["Exodus 3", "Ezekiel 36", "Matthew 3", "Romans 14:17", "Matthew 26:39"],
    book: "Matthew",
  },

  // ── OT Revisited ───────────────────────────────────────────────────────────
  {
    id: "otr-saul",
    youtubeId: "fNqEYB4QHCA",
    title: "Insecurity and Saul",
    series: "OT Revisited",
    seriesId: "ot-revisited",
    speaker: "Curtis Hill",
    date: "2026-06-29",
    passage: "Selected Scriptures from 1 Samuel",
    passages: ["1 Samuel 13", "1 Samuel 16", "Philippians 3:4-14", "1 Corinthians 15:9-10", "Galatians 2:20"],
    book: "1 Samuel",
  },
  {
    id: "otr-hezekiah",
    youtubeId: "qpkFmfTK7NI",
    title: "Great Starts, Unsuccessful Finishes",
    series: "OT Revisited",
    seriesId: "ot-revisited",
    speaker: "Curtis Hill",
    date: "2026-06-22",
    passage: "2 Kings 18–20",
    passages: ["2 Kings 18-20", "2 Chronicles 29-32", "Isaiah 36-39", "2 Chronicles 29:2", "2 Chronicles 31:20-21"],
    book: "2 Kings",
  },
  {
    id: "sing-to-the-lord",
    youtubeId: "",
    title: "Sing to the Lord",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2026-06-07",
    passage: "Selected Psalms",
    book: "Psalms",
  },
  {
    id: "otr-elijah",
    youtubeId: "5L2MThCzwS0",
    title: "Unanswered Prayers",
    series: "OT Revisited",
    seriesId: "ot-revisited",
    speaker: "Curtis Hill",
    date: "2026-06-08",
    passage: "1 Kings 19",
    passages: ["Psalm 13", "Psalm 42:8", "Psalm 145", "Psalm 62", "Psalm 42"],
    book: "1 Kings",
  },

  // ── Complete in Christ (Colossians) ────────────────────────────────────────
  {
    id: "col-11",
    youtubeId: "PJ4xu0Hi7pk",
    title: "A Gospel Team",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-06-01",
    passage: "Colossians 4:7–18",
    passages: ["Acts 13", "Acts 15", "Acts 19-20", "Acts 28:31", "2 Timothy 4:11"],
    book: "Colossians",
  },
  {
    id: "col-10",
    youtubeId: "espt6wDDlN8",
    title: "Devoted to Prayer",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Micah Frink",
    date: "2026-05-25",
    passage: "Colossians 4:2–6",
    book: "Colossians",
  },
  {
    id: "col-9",
    youtubeId: "0oj7GUyU4GI",
    title: "Whatever You Do",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-05-18",
    passage: "Colossians 3:18–4:1",
    book: "Colossians",
  },
  {
    id: "col-8",
    youtubeId: "eEJmdxvrrQI",
    title: "Peace and the Word",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-05-11",
    passage: "Colossians 3:12–17",
    passages: ["Colossians 3:12-17", "Colossians 3"],
    book: "Colossians",
  },
  {
    id: "col-7",
    youtubeId: "FuDNdK4eCtI",
    title: "Mapping Your Story to His",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-05-04",
    passage: "Colossians 3:1–11",
    passages: ["Colossians 3:1-11"],
    book: "Colossians",
  },
  {
    id: "col-6",
    youtubeId: "kaSwWfM7fDU",
    title: "The Limits of Legalism",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-04-27",
    passage: "Colossians 2:16–23",
    passages: ["Colossians 2:16-23", "Colossians 1-2"],
    book: "Colossians",
  },
  {
    id: "col-5",
    youtubeId: "PZ_uSwov-O8",
    title: "Serious Conversations",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-04-20",
    passage: "Colossians 2:4–15",
    book: "Colossians",
  },
  {
    id: "col-4",
    youtubeId: "jyRVwgydS3A",
    title: "Core Drives",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-04-13",
    passage: "Colossians 1:24–2:3",
    passages: ["Colossians 1:24-2", "Colossians 2:2-3"],
    book: "Colossians",
  },
  {
    id: "easter-2026",
    youtubeId: "OZrY_op70b8",
    title: "Easter Expectations",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-04-05",
    passage: "Luke 24:13–27",
    book: "Luke",
  },
  {
    id: "col-3",
    youtubeId: "wZHGl48xcww",
    title: "The Center of Everything",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-03-29",
    passage: "Colossians 1:15–23",
    passages: ["Colossians 1:15-20", "John 1:18", "Hebrews 1:3", "Psalm 89 - 20", "2 Corinthians 5"],
    book: "Colossians",
  },
  {
    id: "col-2",
    youtubeId: "38gQ6T3agiM",
    title: "A Great Big Prayer",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-03-22",
    passage: "Colossians 1:9–14",
    passages: ["Colossians 1", "Colossians 1:9-14", "Philippians 3", "Psalm 13:20"],
    book: "Colossians",
  },
  {
    id: "col-1",
    youtubeId: "BTLyqXXvkvQ",
    title: "The Most Important Thing Happening",
    series: "Complete in Christ",
    seriesId: "complete-in-christ",
    speaker: "Curtis Hill",
    date: "2026-03-15",
    passage: "Colossians 1:1–8",
    passages: ["Colossians 1:1-8"],
    book: "Colossians",
  },

  // ── God's Work | Our Work ──────────────────────────────────────────────────
  {
    id: "gw-5",
    youtubeId: "IM5DeRDpr6w",
    title: "Stewarding Our Heritage",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-03-08",
    passage: "Psalm 90",
    passages: ["Psalm 90", "Matthew 25:14-28"],
    book: "Psalms",
  },
  {
    id: "gw-4",
    youtubeId: "pG0r3Y5Kihc",
    title: "Reaching Our Region",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-03-01",
    passage: "1 Thessalonians 1",
    passages: ["Romans 5:8", "2 Corinthians 5:14-15", "1 Peter 2:9", "Acts 16", "Acts 2:47"],
    book: "1 Thessalonians",
  },
  {
    id: "gw-guest-0222",
    youtubeId: "ROFTKtJ_O2Q",
    title: "Luke 8",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Jackson Bowman",
    date: "2026-02-22",
    passage: "Luke 8",
    book: "Luke",
  },
  {
    id: "gw-3",
    youtubeId: "b8QmPi42yHk",
    title: "Embracing Our Work",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-02-15",
    passage: "Nehemiah 3; Romans 16",
    passages: ["Nehemiah 3", "Romans 16", "Nehemiah 4:6", "Ephesians 2:8-10", "Ephesians 4:29"],
    book: "Nehemiah",
  },
  {
    id: "gw-1",
    youtubeId: "mswliqGNPBI",
    title: "Burdens and a Big Prayer",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-01-19",
    passage: "Psalm 90:12–17",
    passages: ["Psalm 90:12-17", "Acts 2", "Acts 9"],
    book: "Psalms",
  },
  {
    id: "gw-2",
    youtubeId: "VLzTn8WEdAA",
    title: "Growing in Our Closeness",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-02-08",
    passage: "Philippians 1:1–11",
    passages: ["John 13:1", "John 15", "Mark 10:21", "John 21", "1 Thessalonians 3:12"],
    book: "Philippians",
  },
  {
    id: "gw-bridge",
    youtubeId: "Gl6AahtL4zk",
    title: "At His Feet, Listening to His Word",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-01-25",
    passage: "Luke 10:38–42",
    passages: ["Luke 10:38-42"],
    book: "Luke",
  },
  {
    id: "gw-guest-0111",
    youtubeId: "lhClPOh1EHw",
    title: "Psalm 8",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Micah Frink",
    date: "2026-01-11",
    passage: "Psalm 8",
    book: "Psalms",
  },
  {
    id: "gw-0104",
    youtubeId: "",
    title: "Prayers We Can Always Pray",
    series: "God's Work | Our Work",
    seriesId: "gods-work-our-work",
    speaker: "Curtis Hill",
    date: "2026-01-04",
    passage: "Luke 11:1–13",
    book: "Luke",
  },

  // ── Advent 2025 — Who Is Jesus? ────────────────────────────────────────────
  {
    id: "advent-2025-4",
    youtubeId: "",
    title: "Jesus the Redeemer",
    series: "Who Is Jesus?",
    seriesId: "who-is-jesus-2025",
    speaker: "Curtis Hill",
    date: "2025-12-21",
    passage: "Galatians 4:4–6",
    book: "Galatians",
  },
  {
    id: "advent-2025-3",
    youtubeId: "",
    title: "Jesus the Word",
    series: "Who Is Jesus?",
    seriesId: "who-is-jesus-2025",
    speaker: "Curtis Hill",
    date: "2025-12-14",
    passage: "John 1:1–18",
    book: "John",
  },
  {
    id: "advent-2025-2",
    youtubeId: "",
    title: "Jesus the Servant",
    series: "Who Is Jesus?",
    seriesId: "who-is-jesus-2025",
    speaker: "Curtis Hill",
    date: "2025-12-07",
    passage: "Philippians 2:1–11",
    book: "Philippians",
  },
  {
    id: "advent-2025-1",
    youtubeId: "",
    title: "Jesus the Son",
    series: "Who Is Jesus?",
    seriesId: "who-is-jesus-2025",
    speaker: "Curtis Hill",
    date: "2025-11-30",
    passage: "Hebrews 1:1–4",
    book: "Hebrews",
  },

  // ── Matthew 6 — Nov 2025 ──────────────────────────────────────────────────
  {
    id: "matt6-3",
    youtubeId: "",
    title: "How to Trust",
    series: "The Ordered Life",
    seriesId: "ordered-life",
    speaker: "Curtis Hill",
    date: "2025-11-23",
    passage: "Matthew 6:25–34",
    book: "Matthew",
  },
  {
    id: "matt6-2",
    youtubeId: "",
    title: "How to Fast",
    series: "The Ordered Life",
    seriesId: "ordered-life",
    speaker: "Curtis Hill",
    date: "2025-11-16",
    passage: "Matthew 6:16–24",
    book: "Matthew",
  },
  {
    id: "matt6-1",
    youtubeId: "",
    title: "How to Give",
    series: "The Ordered Life",
    seriesId: "ordered-life",
    speaker: "Curtis Hill",
    date: "2025-11-02",
    passage: "Matthew 6:1–4",
    book: "Matthew",
  },

  // ── Standalone — Oct 2025 ──────────────────────────────────────────────────
  {
    id: "harvest-2025",
    youtubeId: "",
    title: "Looking at the Harvest",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2025-10-26",
    passage: "Matthew 9",
    book: "Matthew",
  },

  // ── Joseph (Genesis) ───────────────────────────────────────────────────────
  {
    id: "joseph-11",
    youtubeId: "",
    title: "God's Good Plan",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-10-19",
    passage: "Genesis 49–50",
    book: "Genesis",
  },
  {
    id: "joseph-10",
    youtubeId: "",
    title: "Blessings",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-10-12",
    passage: "Genesis 48",
    book: "Genesis",
  },
  {
    id: "joseph-9",
    youtubeId: "",
    title: "These Are the Names",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-10-05",
    passage: "Genesis 46–47",
    book: "Genesis",
  },
  {
    id: "joseph-8",
    youtubeId: "",
    title: "Connecting the Dots",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-09-28",
    passage: "Genesis 45–46",
    book: "Genesis",
  },
  {
    id: "joseph-7",
    youtubeId: "",
    title: "The Gospel According to Judah",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-09-21",
    passage: "Genesis 43–44",
    book: "Genesis",
  },
  {
    id: "joseph-6",
    youtubeId: "",
    title: "Above and Beyond",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-09-14",
    passage: "Genesis 42",
    book: "Genesis",
  },
  {
    id: "joseph-5",
    youtubeId: "",
    title: "Navigating Success",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-09-07",
    passage: "Genesis 41",
    book: "Genesis",
  },
  {
    id: "joseph-4",
    youtubeId: "",
    title: "Pressure and Time",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-08-31",
    passage: "Genesis 40",
    book: "Genesis",
  },
  {
    id: "joseph-3",
    youtubeId: "",
    title: "Stabilizing Your Soul",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-08-24",
    passage: "Genesis 39",
    book: "Genesis",
  },
  {
    id: "joseph-2",
    youtubeId: "",
    title: "Dissecting a Disaster",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-08-17",
    passage: "Genesis 37",
    book: "Genesis",
  },
  {
    id: "joseph-1",
    youtubeId: "",
    title: "Joseph",
    series: "Providence",
    seriesId: "joseph",
    speaker: "Curtis Hill",
    date: "2025-08-10",
    passage: "Selected Scriptures",
    book: "Genesis",
  },

  // ── Standalone — Aug 2025 ─────────────────────────────────────────────────
  {
    id: "psalm-51-2025",
    youtubeId: "",
    title: "Repentance",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2025-08-03",
    passage: "Psalm 51",
    book: "Psalms",
  },

  // ── Gospel of John ────────────────────────────────────────────────────────
  {
    id: "john-11",
    youtubeId: "jKJRAh_vlDc",
    title: "Responding to Jesus",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-07-27",
    passage: "John 8:48–59",
    book: "John",
  },
  {
    // No real title on file for this guest message — using the passage as an
    // honest placeholder until a transcript/title is provided (same
    // convention as the Dec2022–Dec2024 backfill).
    id: "john-10c",
    youtubeId: "lgjcK4N3MWE",
    title: "John 8:30–47",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Jackson Bowman",
    date: "2025-07-20",
    passage: "John 8:30–47",
    book: "John",
  },
  {
    // Same placeholder-title situation as above.
    id: "john-10b",
    youtubeId: "jg5MIxDv43I",
    title: "John 8",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Josiah King",
    date: "2025-07-13",
    passage: "John 8",
    book: "John",
  },
  {
    id: "john-10",
    youtubeId: "Bf-1shmYluU",
    title: "Neither Do I",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-07-06",
    passage: "John 8:1–11",
    book: "John",
  },
  {
    id: "john-9",
    youtubeId: "",
    title: "The Holy Spirit",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-06-29",
    passage: "John 7:37–39",
    book: "John",
  },
  {
    id: "john-8",
    youtubeId: "",
    title: "All Who Are Thirsty",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-06-22",
    passage: "John 7:25–39",
    book: "John",
  },
  {
    id: "john-7",
    youtubeId: "",
    title: "People Who Should Get It",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-06-15",
    passage: "John 7:1–24",
    book: "John",
  },
  {
    id: "john-6",
    youtubeId: "",
    title: "You Don't Want to Go Away",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-06-08",
    passage: "John 6:30–71",
    book: "John",
  },
  {
    id: "john-5",
    youtubeId: "",
    title: "King-Makers, Chaos and Food-Chasers",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-05-25",
    passage: "John 6:14–29",
    book: "John",
  },
  {
    id: "john-4",
    youtubeId: "",
    title: "Bringing Jesus into the Equation",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-05-18",
    passage: "John 6:1–14",
    book: "John",
  },
  {
    id: "john-3",
    youtubeId: "",
    title: "Initiation of a Confrontation",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-05-11",
    passage: "John 5:31–47",
    book: "John",
  },
  {
    id: "john-2",
    youtubeId: "",
    title: "Father and Son",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-05-04",
    passage: "John 5:17–29",
    book: "John",
  },
  {
    id: "john-1",
    youtubeId: "",
    title: "Jesus Notices Hurting People",
    series: "Gospel of John",
    seriesId: "gospel-of-john",
    speaker: "Curtis Hill",
    date: "2025-04-27",
    passage: "John 5:1–14",
    book: "John",
  },

  // ── Standalone — Spring 2025 ──────────────────────────────────────────────
  {
    id: "easter-2025",
    youtubeId: "",
    title: "Easter",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2025-04-20",
    passage: "1 Peter 1:3–9",
    book: "1 Peter",
  },
  {
    id: "isaiah-40-2025",
    youtubeId: "",
    title: "Bookmark",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2025-04-06",
    passage: "Isaiah 40",
    book: "Isaiah",
  },

  // ── Ecclesiastes ──────────────────────────────────────────────────────────
  {
    id: "eccl-6",
    youtubeId: "",
    title: "Wrapping It All Up",
    series: "Under the Sun",
    seriesId: "ecclesiastes",
    speaker: "Curtis Hill",
    date: "2025-03-30",
    passage: "Ecclesiastes 12",
    book: "Ecclesiastes",
  },
  {
    id: "eccl-5",
    youtubeId: "",
    title: "How Do We Remember Death?",
    series: "Under the Sun",
    seriesId: "ecclesiastes",
    speaker: "Curtis Hill",
    date: "2025-03-23",
    passage: "Ecclesiastes 9–11",
    book: "Ecclesiastes",
  },
  {
    id: "eccl-4",
    youtubeId: "",
    title: "What Investments Will You Make?",
    series: "Under the Sun",
    seriesId: "ecclesiastes",
    speaker: "Curtis Hill",
    date: "2025-03-16",
    passage: "Ecclesiastes 5–8",
    book: "Ecclesiastes",
  },
  {
    id: "eccl-3",
    youtubeId: "",
    title: "How Do You Receive a Gift?",
    series: "Under the Sun",
    seriesId: "ecclesiastes",
    speaker: "Curtis Hill",
    date: "2025-03-09",
    passage: "Ecclesiastes 4–5",
    book: "Ecclesiastes",
  },
  {
    id: "eccl-2",
    youtubeId: "",
    title: "What Time Is It?",
    series: "Under the Sun",
    seriesId: "ecclesiastes",
    speaker: "Curtis Hill",
    date: "2025-03-02",
    passage: "Ecclesiastes 3",
    book: "Ecclesiastes",
  },
  {
    id: "eccl-1",
    youtubeId: "",
    title: "Where Are We?",
    series: "Under the Sun",
    seriesId: "ecclesiastes",
    speaker: "Curtis Hill",
    date: "2025-02-23",
    passage: "Ecclesiastes 1–2",
    book: "Ecclesiastes",
  },

  // ── Acts ──────────────────────────────────────────────────────────────────
  {
    id: "acts-6",
    youtubeId: "",
    title: "The God Who Orchestrates",
    series: "The Church on Mission",
    seriesId: "acts-2025",
    speaker: "Curtis Hill",
    date: "2025-02-16",
    passage: "Acts 16–17",
    book: "Acts",
  },
  {
    id: "acts-5",
    youtubeId: "",
    title: "Different and Better",
    series: "The Church on Mission",
    seriesId: "acts-2025",
    speaker: "Curtis Hill",
    date: "2025-02-09",
    passage: "Acts 11:19–30",
    book: "Acts",
  },
  {
    id: "acts-4",
    youtubeId: "",
    title: "Hard Seasons",
    series: "The Church on Mission",
    seriesId: "acts-2025",
    speaker: "Curtis Hill",
    date: "2025-02-02",
    passage: "Acts 4–9",
    book: "Acts",
  },
  {
    id: "acts-3",
    youtubeId: "",
    title: "What Defines Us",
    series: "The Church on Mission",
    seriesId: "acts-2025",
    speaker: "Curtis Hill",
    date: "2025-01-26",
    passage: "Acts 2",
    book: "Acts",
  },
  {
    id: "acts-2",
    youtubeId: "",
    title: "Lord and Messiah",
    series: "The Church on Mission",
    seriesId: "acts-2025",
    speaker: "Curtis Hill",
    date: "2025-01-19",
    passage: "Acts 2",
    book: "Acts",
  },
  {
    id: "acts-1",
    youtubeId: "",
    title: "Devoted to Prayer",
    series: "The Church on Mission",
    seriesId: "acts-2025",
    speaker: "Curtis Hill",
    date: "2025-01-05",
    passage: "Acts 1–2",
    book: "Acts",
  },

  // ── 2022–2024 backfill (Dec 4, 2022 → Dec 29, 2024) ─────────────────────────────────────
  // Pulled from the YouTube "Sermons" playlist. Filtered to current staff
  // (lib/speakers.ts STAFF_ROSTER) minus guest speakers who never joined
  // staff; Kevin Baggett (former interim pastor, pre-Curtis) intentionally
  // excluded throughout, even mid-series, per instruction.
  //
  // IMPORTANT -- these are placeholders, not final data:
  //   - `title` is set to the passage. These uploads never had a real
  //     sermon title on YouTube (just "Month D, YYYY | Speaker | Passage"),
  //     so there is no title text to recover. Replace with the real title
  //     once the transcripts come in.
  //   - `series` is the plain book name (e.g. "Exodus", "John"), not an
  //     invented series title like the named series above (e.g. "OT
  //     Revisited") -- there's no record of what these were actually
  //     called, so the book name is the only thing the data supports.
  //     "John" appears twice (2023 and 2024) because Curtis preached two
  //     separate passes through it; seriesId is suffixed by year so they
  //     don't merge into one series card.
  //   - Entries bucketed into "Guest Messages" are standalone/one-off
  //     messages (topical Psalms, Advent one-offs, Easter, year-end) that
  //     don't belong to a multi-week run -- same convention the current
  //     library already uses for one-offs, regardless of speaker.
  {
    id: "bf-guest-messages-11",
    youtubeId: "IU4sjhyzbGE",
    title: "Isaiah 46",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Micah Frink",
    date: "2024-12-29",
    passage: "Isaiah 46",
    book: "Isaiah",
  },
  {
    id: "bf-matthew-2024-4",
    youtubeId: "Lb49RFGjqoo",
    title: "Matthew 2",
    series: "Matthew",
    seriesId: "matthew-2024",
    speaker: "Curtis Hill",
    date: "2024-12-22",
    passage: "Matthew 2",
    book: "Matthew",
  },
  {
    id: "bf-matthew-2024-3",
    youtubeId: "2qiQCqRDZT4",
    title: "Matthew 1",
    series: "Matthew",
    seriesId: "matthew-2024",
    speaker: "Curtis Hill",
    date: "2024-12-15",
    passage: "Matthew 1",
    book: "Matthew",
  },
  {
    id: "bf-matthew-2024-2",
    youtubeId: "3hlTcMD3TGo",
    title: "Matthew 1:18–24",
    series: "Matthew",
    seriesId: "matthew-2024",
    speaker: "Curtis Hill",
    date: "2024-12-08",
    passage: "Matthew 1:18–24",
    book: "Matthew",
  },
  {
    id: "bf-matthew-2024-1",
    youtubeId: "4k5Fun35R9I",
    title: "Matthew 1",
    series: "Matthew",
    seriesId: "matthew-2024",
    speaker: "Curtis Hill",
    date: "2024-12-01",
    passage: "Matthew 1",
    book: "Matthew",
  },
  {
    id: "bf-john-2024-15",
    youtubeId: "VkM3JB_s4qI",
    title: "John 4:43–54",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-11-24",
    passage: "John 4:43–54",
    book: "John",
  },
  {
    id: "bf-john-2024-14",
    youtubeId: "HUM3d0xKK3Y",
    title: "John 4:27–42",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-11-17",
    passage: "John 4:27–42",
    book: "John",
  },
  {
    id: "bf-john-2024-13",
    youtubeId: "W1HvgTfD7eU",
    title: "John 4",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-11-10",
    passage: "John 4",
    book: "John",
  },
  {
    id: "bf-john-2024-12",
    youtubeId: "LGLiHmkbCS8",
    title: "John 4",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-11-03",
    passage: "John 4",
    book: "John",
  },
  {
    id: "bf-john-2024-11",
    youtubeId: "n1EFIJeXMMM",
    title: "John 3:31–36",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-10-27",
    passage: "John 3:31–36",
    book: "John",
  },
  {
    id: "bf-john-2024-10",
    youtubeId: "WA0lJ6SMG9Q",
    title: "John 3:22–30",
    series: "John",
    seriesId: "john-2024",
    speaker: "Paul Christensen",
    date: "2024-10-20",
    passage: "John 3:22–30",
    book: "John",
  },
  {
    id: "bf-john-2024-9",
    youtubeId: "gS3zaLQtVVU",
    title: "John 2:23–3:9",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-10-06",
    passage: "John 2:23–3:9",
    book: "John",
  },
  {
    id: "bf-john-2024-8",
    youtubeId: "nlntfLTKWZc",
    title: "John 2:12–22",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-09-29",
    passage: "John 2:12–22",
    book: "John",
  },
  {
    id: "bf-john-2024-7",
    youtubeId: "X6wosYaThho",
    title: "John 2:1–12",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-09-22",
    passage: "John 2:1–12",
    book: "John",
  },
  {
    id: "bf-john-2024-6",
    youtubeId: "aZlDWbBwFbI",
    title: "John 1:35–51",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-09-15",
    passage: "John 1:35–51",
    book: "John",
  },
  {
    id: "bf-john-2024-5",
    youtubeId: "ziD5udcAdnc",
    title: "John 1:19–34",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-09-08",
    passage: "John 1:19–34",
    book: "John",
  },
  {
    id: "bf-john-2024-4",
    youtubeId: "7i8I-TTVEPM",
    title: "John 1:14–18",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-09-01",
    passage: "John 1:14–18",
    book: "John",
  },
  {
    id: "bf-john-2024-3",
    youtubeId: "nuG0MNBW1Vc",
    title: "John 1:9–14",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-08-25",
    passage: "John 1:9–14",
    book: "John",
  },
  {
    id: "bf-john-2024-2",
    youtubeId: "ydWiIZzxXm4",
    title: "John 1:6–9",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-08-18",
    passage: "John 1:6–9",
    book: "John",
  },
  {
    id: "bf-john-2024-1",
    youtubeId: "i20PjDsTvBI",
    title: "John 1:1–5",
    series: "John",
    seriesId: "john-2024",
    speaker: "Curtis Hill",
    date: "2024-08-11",
    passage: "John 1:1–5",
    book: "John",
  },
  {
    id: "bf-proverbs-2024-7",
    youtubeId: "awAOdST8KF4",
    title: "Proverbs",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Curtis Hill",
    date: "2024-08-04",
    passage: "Proverbs",
    book: "Proverbs",
  },
  {
    id: "bf-proverbs-2024-6",
    youtubeId: "fU_Io8VZL1I",
    title: "Proverbs 9",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Micah Frink",
    date: "2024-07-28",
    passage: "Proverbs 9",
    book: "Proverbs",
  },
  {
    id: "bf-proverbs-2024-5",
    youtubeId: "lkoScR98BxQ",
    title: "Proverbs 15",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Curtis Hill",
    date: "2024-07-14",
    passage: "Proverbs 15",
    book: "Proverbs",
  },
  {
    id: "bf-proverbs-2024-4",
    youtubeId: "edzBOjTqAPM",
    title: "Proverbs 4",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Curtis Hill",
    date: "2024-07-07",
    passage: "Proverbs 4",
    book: "Proverbs",
  },
  {
    id: "bf-proverbs-2024-3",
    youtubeId: "zIEKUaCjx1M",
    title: "Proverbs 8:1–11",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Curtis Hill",
    date: "2024-06-23",
    passage: "Proverbs 8:1–11",
    book: "Proverbs",
  },
  {
    id: "bf-proverbs-2024-2",
    youtubeId: "-3eMQ2RFheA",
    title: "Proverbs 2",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Curtis Hill",
    date: "2024-06-16",
    passage: "Proverbs 2",
    book: "Proverbs",
  },
  {
    id: "bf-proverbs-2024-1",
    youtubeId: "p7Vk4E-4N4c",
    title: "Proverbs 1",
    series: "Proverbs",
    seriesId: "proverbs-2024",
    speaker: "Curtis Hill",
    date: "2024-06-09",
    passage: "Proverbs 1",
    book: "Proverbs",
  },
  {
    id: "bf-guest-messages-10",
    youtubeId: "nH6D4VmiY8A",
    title: "Psalm 16",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2024-06-02",
    passage: "Psalm 16",
    book: "Psalms",
  },
  {
    id: "bf-2-timothy-2024-7",
    youtubeId: "tKC0-RI96R4",
    title: "2 Timothy 4",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Curtis Hill",
    date: "2024-05-26",
    passage: "2 Timothy 4",
    book: "2 Timothy",
  },
  {
    id: "bf-2-timothy-2024-6",
    youtubeId: "jNyWWwyFYaU",
    title: "2 Timothy 4",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Curtis Hill",
    date: "2024-05-19",
    passage: "2 Timothy 4",
    book: "2 Timothy",
  },
  {
    id: "bf-2-timothy-2024-5",
    youtubeId: "1_IdVAN5FZM",
    title: "2 Timothy 3",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Curtis Hill",
    date: "2024-05-12",
    passage: "2 Timothy 3",
    book: "2 Timothy",
  },
  {
    id: "bf-2-timothy-2024-4",
    youtubeId: "Q84hmFCPbvs",
    title: "2 Timothy 3",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Curtis Hill",
    date: "2024-05-05",
    passage: "2 Timothy 3",
    book: "2 Timothy",
  },
  {
    id: "bf-2-timothy-2024-3",
    youtubeId: "a09ARIi2nrs",
    title: "2 Timothy 2:14–26",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Paul Christensen",
    date: "2024-04-28",
    passage: "2 Timothy 2:14–26",
    book: "2 Timothy",
  },
  {
    id: "bf-2-timothy-2024-2",
    youtubeId: "vxwebxKQ14U",
    title: "2 Timothy 2",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Curtis Hill",
    date: "2024-04-21",
    passage: "2 Timothy 2",
    book: "2 Timothy",
  },
  {
    id: "bf-2-timothy-2024-1",
    youtubeId: "AZWiGCHeX68",
    title: "2 Timothy 1:8–18",
    series: "2 Timothy",
    seriesId: "2-timothy-2024",
    speaker: "Curtis Hill",
    date: "2024-04-14",
    passage: "2 Timothy 1:8–18",
    book: "2 Timothy",
  },
  {
    id: "bf-guest-messages-9",
    youtubeId: "J9S99C2gAis",
    title: "Romans 8",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2024-03-31",
    passage: "Romans 8",
    book: "Romans",
  },
  {
    id: "bf-exodus-2024-11",
    youtubeId: "_tUTzbuTl5s",
    title: "Exodus 40",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-03-24",
    passage: "Exodus 40",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-10",
    youtubeId: "_t5w_-l9v2o",
    title: "Exodus 33",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-03-17",
    passage: "Exodus 33",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-9",
    youtubeId: "4fNc7CDbv-U",
    title: "Exodus 32",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-03-10",
    passage: "Exodus 32",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-8",
    youtubeId: "-tLoio5np4w",
    title: "Exodus 28",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-03-03",
    passage: "Exodus 28",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-7",
    youtubeId: "ItvFVCjtDXU",
    title: "Exodus 20",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-02-18",
    passage: "Exodus 20",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-6",
    youtubeId: "odV-R4Adppk",
    title: "Exodus 24",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-02-11",
    passage: "Exodus 24",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-5",
    youtubeId: "mIkBpXA_HT8",
    title: "Exodus 21",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-02-04",
    passage: "Exodus 21",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-4",
    youtubeId: "QNBMArWLMyU",
    title: "Exodus 20",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-01-28",
    passage: "Exodus 20",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-3",
    youtubeId: "qWrlMU7vq5o",
    title: "Exodus 19",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-01-21",
    passage: "Exodus 19",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-2",
    youtubeId: "t2w7kjTpE_Y",
    title: "Exodus 17",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-01-14",
    passage: "Exodus 17",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2024-1",
    youtubeId: "xlgYzgYeNJA",
    title: "Exodus 15",
    series: "Exodus",
    seriesId: "exodus-2024",
    speaker: "Curtis Hill",
    date: "2024-01-07",
    passage: "Exodus 15",
    book: "Exodus",
  },
  {
    id: "bf-guest-messages-8",
    youtubeId: "BlUNanpsRdw",
    title: "Luke 2",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-12-24",
    passage: "Luke 2",
    book: "Luke",
  },
  {
    id: "bf-guest-messages-7",
    youtubeId: "9TQZ8vVLkXg",
    title: "Isaiah 35",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-12-17",
    passage: "Isaiah 35",
    book: "Isaiah",
  },
  {
    id: "bf-guest-messages-6",
    youtubeId: "43gCalJKw14",
    title: "Psalm 16",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-12-10",
    passage: "Psalm 16",
    book: "Psalms",
  },
  {
    id: "bf-guest-messages-5",
    youtubeId: "4Zpv68aEjP4",
    title: "John 16",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-12-03",
    passage: "John 16",
    book: "John",
  },
  {
    id: "bf-exodus-2023-10",
    youtubeId: "8J0iHzZAMOg",
    title: "Exodus 15",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-11-26",
    passage: "Exodus 15",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-9",
    youtubeId: "37dkicCe91I",
    title: "Exodus 13",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-11-19",
    passage: "Exodus 13",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-8",
    youtubeId: "cd9BW2pM2K4",
    title: "Exodus 12–13",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-11-12",
    passage: "Exodus 12–13",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-7",
    youtubeId: "EHxfVs67dp8",
    title: "Exodus 11–12",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-11-05",
    passage: "Exodus 11–12",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-6",
    youtubeId: "SOKIo7mzvns",
    title: "Exodus 7–11",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-10-29",
    passage: "Exodus 7–11",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-5",
    youtubeId: "xaaVSzapZFc",
    title: "Exodus 5–6",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-10-22",
    passage: "Exodus 5–6",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-4",
    youtubeId: "XVoXBopHXgE",
    title: "Exodus 4",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-10-15",
    passage: "Exodus 4",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-3",
    youtubeId: "jNh3cEgNHbc",
    title: "Exodus 3",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-10-08",
    passage: "Exodus 3",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-2",
    youtubeId: "Rh1mPGdODnk",
    title: "Exodus 1:8–2:10",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Micah Frink",
    date: "2023-09-24",
    passage: "Exodus 1:8–2:10",
    book: "Exodus",
  },
  {
    id: "bf-exodus-2023-1",
    youtubeId: "OHNtXqd7pc4",
    title: "Exodus 1",
    series: "Exodus",
    seriesId: "exodus-2023",
    speaker: "Curtis Hill",
    date: "2023-09-17",
    passage: "Exodus 1",
    book: "Exodus",
  },
  {
    id: "bf-ephesians-2023-11",
    youtubeId: "BpYlpdD2ks4",
    title: "Ephesians 6",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-08-27",
    passage: "Ephesians 6",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-10",
    youtubeId: "5d0SC2Flpzo",
    title: "Ephesians 5",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-08-20",
    passage: "Ephesians 5",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-9",
    youtubeId: "FBEKFfgbwb8",
    title: "Ephesians 5",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-08-13",
    passage: "Ephesians 5",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-8",
    youtubeId: "pACNQPryHdM",
    title: "Ephesians 5",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-08-06",
    passage: "Ephesians 5",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-7",
    youtubeId: "_PfxMrvOp6A",
    title: "Ephesians 4",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-07-30",
    passage: "Ephesians 4",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-6",
    youtubeId: "_Mx90wVzK7E",
    title: "Ephesians 3:1–13",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-07-02",
    passage: "Ephesians 3:1–13",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-5",
    youtubeId: "-8WuD4Fq9CQ",
    title: "Ephesians 2:11–22",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-06-25",
    passage: "Ephesians 2:11–22",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-4",
    youtubeId: "z0WrEKG7FdU",
    title: "Ephesians 2:1–10",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-06-18",
    passage: "Ephesians 2:1–10",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-3",
    youtubeId: "gDBqt5srY2w",
    title: "Ephesians 1:11–14",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-06-04",
    passage: "Ephesians 1:11–14",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-2",
    youtubeId: "zhkHBo1mbZY",
    title: "Ephesians 1:3–10",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-05-28",
    passage: "Ephesians 1:3–10",
    book: "Ephesians",
  },
  {
    id: "bf-ephesians-2023-1",
    youtubeId: "WLU5We_ynSU",
    title: "Ephesians 1:1–2",
    series: "Ephesians",
    seriesId: "ephesians-2023",
    speaker: "Curtis Hill",
    date: "2023-05-21",
    passage: "Ephesians 1:1–2",
    book: "Ephesians",
  },
  {
    id: "bf-guest-messages-4",
    youtubeId: "XxWh05jIgsU",
    title: "Psalm 119",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-05-14",
    passage: "Psalm 119",
    book: "Psalms",
  },
  {
    id: "bf-guest-messages-3",
    youtubeId: "XKE-wYMOHdE",
    title: "Psalm 1",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-05-07",
    passage: "Psalm 1",
    book: "Psalms",
  },
  {
    id: "bf-guest-messages-2",
    youtubeId: "ePlW4NP3dYY",
    title: "Psalm 19",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2023-04-30",
    passage: "Psalm 19",
    book: "Psalms",
  },
  {
    id: "bf-john-2023-10",
    youtubeId: "VFvsHAs2xBU",
    title: "John 21",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-04-23",
    passage: "John 21",
    book: "John",
  },
  {
    id: "bf-john-2023-9",
    youtubeId: "KvCr4lkOhS8",
    title: "John 20",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-04-16",
    passage: "John 20",
    book: "John",
  },
  {
    id: "bf-john-2023-8",
    youtubeId: "7mxQJDIYQd0",
    title: "John 17",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-04-02",
    passage: "John 17",
    book: "John",
  },
  {
    id: "bf-john-2023-7",
    youtubeId: "adS9iNjFnvY",
    title: "John 17",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-03-26",
    passage: "John 17",
    book: "John",
  },
  {
    id: "bf-john-2023-6",
    youtubeId: "QfwKoK5MVgw",
    title: "John 16",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-03-19",
    passage: "John 16",
    book: "John",
  },
  {
    id: "bf-john-2023-5",
    youtubeId: "Q6lbboGsopY",
    title: "John 15",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-03-12",
    passage: "John 15",
    book: "John",
  },
  {
    id: "bf-john-2023-4",
    youtubeId: "YFBXhKsDIQA",
    title: "John 14",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-02-26",
    passage: "John 14",
    book: "John",
  },
  {
    id: "bf-john-2023-3",
    youtubeId: "TaXEt8M0y54",
    title: "John 13",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-02-19",
    passage: "John 13",
    book: "John",
  },
  {
    id: "bf-john-2023-2",
    youtubeId: "2I3YfjJMqa4",
    title: "John 13",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-02-12",
    passage: "John 13",
    book: "John",
  },
  {
    id: "bf-john-2023-1",
    youtubeId: "znlJ9bhusOc",
    title: "John 13",
    series: "John",
    seriesId: "john-2023",
    speaker: "Curtis Hill",
    date: "2023-02-05",
    passage: "John 13",
    book: "John",
  },
  {
    id: "bf-guest-messages-1",
    youtubeId: "UWvhjxtXHig",
    title: "Romans 16",
    series: "Guest Messages",
    seriesId: "guest-messages",
    speaker: "Curtis Hill",
    date: "2022-12-04",
    passage: "Romans 16",
    book: "Romans",
  },

];

// ── Series metadata ───────────────────────────────────────────────────────────

export const SERIES_META: Record<string, {
  description: string
  passage?: string
}> = {
  "behind-the-scenes": {
    description: "The book of Esther never mentions God by name — yet every scene is saturated with his providence. In this series we trace the unseen hand of God working through ordinary people caught in an extraordinary moment.",
    passage: "Esther",
  },
  "prayer-that-shapes-us": {
    description: "A verse-by-verse walk through the Lord's Prayer in Matthew 6. What does it look like to pray in a way that actually reshapes how you see God, yourself, and the world around you?",
    passage: "Matthew 6",
  },
  "ot-revisited": {
    description: "Three figures from the Old Testament — Elijah, Hezekiah, and Saul — each offer a window into the human condition and the grace of God that meets us there.",
    passage: "Selected OT passages",
  },
  "complete-in-christ": {
    description: "Paul's letter to the Colossians confronts anything that competes with Christ. This series works through the whole letter, making the case that Jesus is enough — completely enough.",
    passage: "Colossians",
  },
  "gods-work-our-work": {
    description: "What does it look like to be a church on mission together? This series roots our collective work in the character and purposes of God.",
  },
  "guest-messages": {
    description: "Standalone messages from guest speakers.",
  },
  "who-is-jesus-2025": {
    description: "Advent 2025. Four portraits of Jesus from the New Testament — Son, Servant, Word, and Redeemer — each asking us to consider who he truly is.",
    passage: "Selected Scriptures",
  },
  "ordered-life": {
    description: "Jesus's teaching in Matthew 6 on the hidden disciplines — giving, fasting, and trusting — that quietly shape the soul.",
    passage: "Matthew 6",
  },
  "joseph": {
    description: "The story of Joseph in Genesis is a long arc of suffering, faithfulness, and stunning reversal. Providence is the thread running through every scene.",
    passage: "Genesis 37–50",
  },
  "gospel-of-john": {
    description: "A summer walk through John 5–8, watching Jesus encounter broken people, skeptical crowds, and thirsty seekers — and responding to each one.",
    passage: "John 5–8",
  },
  "ecclesiastes": {
    description: "Qohelet's restless search for meaning under the sun leads to the same place every honest search does. This series asks his questions and listens for his answers.",
    passage: "Ecclesiastes",
  },
  "acts-2025": {
    description: "What does it mean to be the church on mission? The early chapters of Acts show us a community defined not by their programs but by their Lord.",
    passage: "Acts 1–17",
  },
}

// ── Derived lists for filter dropdowns ────────────────────────────────────────

export const ALL_SERIES = Array.from(
  new Map(SERMONS.map((s) => [s.seriesId, s.series])).entries()
).map(([id, name]) => ({ id, name }));

export const ALL_SPEAKERS = Array.from(new Set(SERMONS.map((s) => s.speaker)));

export const ALL_YEARS = Array.from(
  new Set(SERMONS.map((s) => s.date.slice(0, 4)))
).sort((a, b) => Number(b) - Number(a));

// ── YouTube helpers ───────────────────────────────────────────────────────────

export function thumbnailUrl(youtubeId: string): string {
  if (!youtubeId) return "";
  return `https://i.ytimg.com/vi/${youtubeId}/hqdefault.jpg`;
}

export function watchUrl(youtubeId: string): string {
  if (!youtubeId) return "/sermons";
  return `https://www.youtube.com/watch?v=${youtubeId}`;
}

export function formatDate(iso: string): string {
  return new Date(iso + "T12:00:00").toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// ── Bible book order ─────────────────────────────────────────────────────────
// Canonical Genesis -> Revelation order, so a "Book" filter reads the way a
// Bible's table of contents does instead of alphabetically (which would
// scatter "1 Samuel" / "2 Timothy" by their digit and split a testament up).

export const BIBLE_BOOK_ORDER: string[] = [
  "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
  "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings", "2 Kings",
  "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Esther",
  "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Solomon",
  "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel",
  "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum",
  "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi",
  "Matthew", "Mark", "Luke", "John", "Acts", "Romans",
  "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians",
  "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians",
  "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews", "James",
  "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude", "Revelation",
];

/** Sorts book names into canonical Bible order; anything unrecognized sorts last, alphabetically. */
export function sortByBibleOrder(books: string[]): string[] {
  return [...books].sort((a, b) => {
    const ia = BIBLE_BOOK_ORDER.indexOf(a);
    const ib = BIBLE_BOOK_ORDER.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b);
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
}
